name: Pull Cataclysm-DDA data

on:
  schedule:
    - cron: '40 */12 * * *'
  workflow_dispatch: {}

jobs:
  pull-data:
    name: Pull Cataclysm-DDA data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: yarn
      - run: npx zx pull-data.mjs
      - run: |
          git config --global user.name 'HHG2C Update Bot'
          git config --global user.email 'hhg2c@users.noreply.github.com'
          git add data builds.json latest-build.json
          git commit -am "Update data" && git push || true
